MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
  WEIGHTS: "models/GTR_5FISH_10000.pth"
DATASETS:
  TRAIN: ("fish_train",)
  TEST: ("fish_val",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0005
  MAX_ITER: 5000
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  
VIDEO_INPUT: True
DATASETS:
  TRAIN: ("fish_train",)
  TEST: ("fish_val",)
DATALOADER:
  SAMPLER_TRAIN: "TrainingSampler"
OUTPUT_DIR: "./output/FISH"
FIND_UNUSED_PARAM: True